#!/bin/bash

echo "##########################################################"
echo "Making "update_ucaresystem-core" exeutble to copy to '/usr/local/bin'"
chmod +x update_ucaresystem-core
sleep 2
# Now I can copy the file using the 'cp' command
echo "Now we can copy the file using the 'cp' command"
sleep 2
sudo cp update_ucaresystem-core /usr/local/bin
echo "Checking if the copy was successful"
sleep 3
# Check if the copy was successful
if [ $? -eq 0 ]; then
  echo "File successfully copied"
else
  echo "Error copying file"
fi
echo ""
echo ""
echo "##########################################################"
echo "Making "upgrade_ucaresystem-core" exeutble to copy to '/usr/local/bin'"
chmod +x upgrade_ucaresystem-core
sleep 2
# Now I can copy the file using the 'cp' command
echo "Now we can copy the file using the 'cp' command"
sleep 2
sudo cp upgrade_ucaresystem-core /usr/local/bin
echo "Checking if the copy was successful"
sleep 3
# Check if the copy was successful
if [ $? -eq 0 ]; then
  echo "File successfully copied"
else
  echo "Error copying file"
fi
echo ""
echo ""
echo "##########################################################"
echo "Making "uit" exeutble to copy to '/usr/local/bin'"
chmod +x uit
sleep 2
# Now I can copy the file using the 'uit' command
echo "Now we can copy the file using the 'UIT' command"
sleep 2
sudo cp uit /usr/local/bin
echo "Checking if the copy was successful"
sleep 3
# Check if the copy was successful
if [ $? -eq 0 ]; then
  echo "File "uit" successfully copied"
else
  echo "Error "uit" copying file"
fi
echo ""
echo ""
echo "##########################################################"
echo "Install " #
sleep 2
# Verlaag de swappiness-waarde naar 5
echo "Verlagen van swappiness-waarde naar 5..."
sudo sysctl vm.swappiness=5

# Controleer of de wijziging is doorgevoerd
echo "Controleren of de swappiness-waarde is verlaagd..."
current_swappiness=$(cat /proc/sys/vm/swappiness)
if [ "$current_swappiness" -eq 5 ]; then
    echo "Swappiness-waarde is succesvol verlaagd naar 5."
else
    echo "Er is een probleem opgetreden bij het verlagen van de swappiness-waarde."
fi

# Maak de wijziging permanent
echo "De nieuwe instellingen permanent maken..."
echo "vm.swappiness=5" | sudo tee -a /etc/sysctl.conf > /dev/null

# Laden van nieuwe instellingen
echo "Nieuwe instellingen toepassen..."
sudo sysctl -p

# Opnieuw controleren of de wijziging permanent is
echo "Opnieuw controleren van de swappiness-waarde..."
current_swappiness=$(cat /proc/sys/vm/swappiness)
if [ "$current_swappiness" -eq 5 ]; then
    echo "Swappiness-waarde is permanent ingesteld op 5."
else
    echo "Er is een probleem opgetreden bij het permanent instellen van de swappiness-waarde."
fi
echo ""
echo ""
echo "##########################################################"
# Update package lists en installeer essentiële updates
sudo apt update
sudo apt upgrade -y

# Installeer Visual Studio Code
echo "Installing Visual Studio Code..."
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
sudo apt update
sudo apt install code -y

# Opruimen
rm microsoft.gpg

echo "Visual Studio Code installation complete."
echo "##########################################################"
echo "Install Github Desktop " #
sleep 2
wget -O github-desktop.deb https://github.com/shiftkey/desktop/releases/download/release-2.8.3-linux1/GitHubDesktop-linux-2.8.3-linux1.deb
sudo dpkg -i github-desktop.deb
sudo apt install -f
echo ""
echo ""
echo "##########################################################"
echo "Turn on the firewall" #sudo ufw disable - to disable the firewall
sleep 2
sudo ufw enable
echo ""
echo ""
echo "##########################################################"
echo "Refresh available updates" #This will refresh available updates
sleep 2
sudo apt-get update -yy
echo ""
echo ""
echo "##########################################################"
echo "Upgrade all packages" #This will Upgrade all packages
sleep 2
sudo apt-get upgrade -yy
echo ""
echo ""
echo "##########################################################"
echo "Install Caffeine" #Caffeine keeps your monitor awake
sleep 2
sudo apt-get install caffeine -yy
echo ""
echo ""
echo "#########################################################"
echo "Install variety" #Variety is the best besktop background manager
sleep 2
sudo apt install variety -yy
echo ""
echo ""
echo "##########################################################"
echo "Install Gparted" #Gparted lets you set partitions 
sleep 2
sudo apt install gparted -yy
echo ""
echo ""
echo "##########################################################"
echo "Install Gimp" # Gimp is the best photo editor 
sleep 2
sudo apt install gimp -yy
echo ""
echo ""
echo "##########################################################"
echo "Install Plank" #Plank is an good icon dock 
sleep 2
sudo apt install plank -yy
sleep 1
# Now we can copy the file using the 'cp' command
echo "Now we can copy the file using the 'cp' command"
sleep 2
cp plank.desktop ~/.config/autostart
echo "Checking if the copy was successful"
sleep 3
# Check if the copy was successful
if [ $? -eq 0 ]; then
  echo "File successfully copied"
else
  echo "Error copying file"
fi
echo ""
echo ""
echo "##########################################################"
echo "Install Nemo" #Neno is an simple but good commandline editor
sleep 2
sudo apt install nemo -yy
echo ""
echo ""
echo "##########################################################"
echo "Install dconf-editor, git, dmenu, flameshot, sublime-text, simplescreenrecorder" #
sudo apt install -yy dconf-editor
sleep 2
sudo apt install -yy git
sleep 2
sudo apt install -yy neofetch
sleep 2
sudo apt install -yy dmenu
sleep 2
sudo apt install -yy flameshot
sleep 2
sudo apt install -yy sublime-text
sleep 2
sudo apt install -yy simplescreenrecorder
sleep 2
#Installed via keys and repo add
sudo apt install -yy atom
sleep 2
sudo apt install -yy code
sleep 2
sudo apt install -yy spotify-client
sleep 2
echo ""
echo ""
echo "##########################################################"
echo "Install preload" #Preload lets your programms load faster
sleep 2
sudo apt install preload -yy
echo ""
echo ""
echo "##########################################################"
echo "Install Discord" #Discord is Discord 
sleep 2
wget -O ~/discord.deb https://discord.com/api/download?platform=linux&format=deb
sudo dpkg -i ~/discord.deb
sudo apt --fix-broken install
echo ""
echo ""
echo "##########################################################"
echo "installing Kodi" #Kodi is a good mediapalyer
sleep 2
sudo apt install software-properties-common 
sudo add-apt-repository -ysP team-xbmc/ppa
sudo apt install kodi -yy
echo ""
echo ""
echo "##########################################################"
echo "Installing U-care-system-core" #ucaresystem-core is een update en schoonmaak programma voor Ubuntu based linux via de terminal
sleep 2
sudo add-apt-repository ppa:utappia/stable
sudo apt-get update
sudo apt-get install ucaresystem-core -yy
echo ""
echo ""
echo "##########################################################"
echo "Installing Stacer" #Stacer is een system monitor
sleep 2
sudo add-apt-repository ppa:oguzhaninan/stacer -y
sudo apt-get update
sudo apt-get install stacer -yy
echo ""
echo ""
echo "##########################################################"
echo "Installing gdebi" #Gdebi is a utility tool that works as an alternative to your default Software Center for installing applications – specifically, .deb packages while resolving and installing its dependencies and you can use it right from your terminal.
sleep 2
sudo apt-get install gdebi -yy
echo ""
echo ""
echo "##########################################################"
echo "Install Ubuntu Restricted Extras (Media Codecs):" #This are some codecs you need down the road of music and video 
sleep 2
sudo apt install ubuntu-restricted-extras -yy
echo ""
echo ""
echo "##########################################################"
echo "Install Htop" #this a nice commandline system monitor
sleep 2
sudo apt update && sudo apt upgrade -yy
sudo apt-get htop
echo ""
echo ""
echo "##########################################################"
echo "######################Remove some software################"
echo "##########################################################"
sleep 2
sudo apt remove -yy hexchat
#echo ""
#echo ""
#echo "##########################################################"
echo ""
echo ""
echo "##########################################################"
echo "#############All done now, you can type exit##############"
echo "##########################################################"
#echo "THIS IS A NEW BLOCK FOR NEW CODE, JUST COPY AND PASTE"
#echo "Install " #
#sleep 2
#sudo apt install  -yy
#echo ""
#echo ""
#echo "##########################################################"
